sudo: required
os: linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake >= 3
    packages:
      - fakeroot
      - cmake
      - cmake-data
      - texinfo # Contains makeinfo that is required to build libconfig
language: c
compiler: clang
env:
  - secure: "Nda6YrVena8n4idioQcGup4/CEMIBXd1XXq/ug6yYEqn7So5eHnU3z5KyN+s/VZcPNA3xLf21SZz3YrJwXW9KSGGTpRV8bpuPr0MjDPS5Dap53xWVYWetL0ATvL63Lpoc1cPgOzxlmAy96uHYdH4T8Yfa6qdVwHYsfGdr+IYhnRkGSBWyI/GBEcv4Tb9mhbuhSmZY3q5eCwRyjJ0j5jkJG4vW5bz5FkCsonPYQVaioga8zXcCdunc4SIAPUJXoNjHrjUSKiL+S7hr0qDX4x6Bu125OIJHsD0Ovj9WbAHZwalrTt6MdWe0unQhIEdpZgETtEkqS1j3J3YiGpC6vDu26bpZqxZKajvowhr7eqcr26a6nnqhuompOnaitBlMxwluNh7plLGb1CdZoZOVd5Y6cnMt4BjPkrr1V5GW5Xczk+0BIPM+swftvGX3Z690cqz2SPptEL5SAshCB8obo6vF7OfVLCto+FooseJ1FQfJL1IMnSY39x3DhQ7icJ43+rq9EFGCoxaVSxLhDSUE3p7gUm/zIdf+j83prt5o29b6FwOrkitESja//hWdIWvHttfr39UEPpcr9+fvVOwBNmew0utSP6iK9/2lroLyy62c4Rz4oWTkRZNjto4nafPaH0HyFKzDZ2J5u3FQ73wODttIRleNtnYjgeifUIzKxedw48="

notifications:
  email: false

before_install:
  - source ./travis_prepare.sh

script:
  - ./travis_build.sh
  - ./travis_upload.sh
